## Lab02 - numpy
Name: Anh Kieu  
Class: CSCI 349 - Intro to Data Mining  
Semester: Spring 2021  
Instructor: Brian King  

In [1]:
import sys
import numpy as np
print(sys.version)
print(np.__version__)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
1.19.2


#### 1. [P] Create a 52500 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 significant digits.

In [2]:
X = np.zeros((52500,75))
print(f"Shape of X is {str(X.shape)}.")
print(f"Base data type of X is {str(X.dtype)}.")
print(f"Individual item size of X is {str(X.itemsize)} bytes.")
print(f"Total item size of X is {str(X.nbytes)} bytes.")
print("Total item size of X in MB is {:.3f} MB.".format(X.nbytes/10**6))

Shape of X is (52500, 75).
Base data type of X is float64.
Individual item size of X is 8 bytes.
Total item size of X is 31500000 bytes.
Total item size of X in MB is 31.500 MB.


#### 2. [P] Resize X to have the same number of elements, but with 100 columns. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [3]:
X.reshape(525*75,100)
print(f"Shape of X is {str(X.shape)}.")
print(f"Total item size of X is {str(X.nbytes)} bytes.")

Shape of X is (52500, 75).
Total item size of X is 31500000 bytes.


#### 3. [P] Redo #1, but use a base datatype of 16-bit integers.

In [4]:
X = np.zeros((52500,75), dtype = np.int16)
print(f"Shape of X is {str(X.shape)}.")
print(f"Base data type of X is {str(X.dtype)}.")
print(f"Individual item size of X is {str(X.itemsize)} bytes.")
print(f"Total item size of X is {str(X.nbytes)} bytes.")
print("Total item size of X in MB is {:.3f} MB.".format(X.nbytes/10**6))

Shape of X is (52500, 75).
Base data type of X is int16.
Individual item size of X is 2 bytes.
Total item size of X is 7875000 bytes.
Total item size of X in MB is 7.875 MB.


#### 4. [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [5]:
print(f"X has {X.ndim} dimensions.")

X has 2 dimensions.


#### 5. [P] Enter the following Python list in your cell:
<code>str_nums = ['2.14', '-9.300', '42']</code>
#### Convert this to a numpy array named X. What is the base type? Show the contents of X.
#### Then, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again.

In [6]:
str_nums = ['2.14', '-9.300', '42']
X = np.array(str_nums)
print(f"Base type of X is {X.dtype}.")
print(X)
print("After conversion: ")
X = X.astype(np.single)
print(X)

Base type of X is <U6.
['2.14' '-9.300' '42']
After conversion: 
[ 2.14 -9.3  42.  ]


#### 6. [P] Copy the three definitions above for the Python lists days, scores_1, and scores_2. Create a numpy array called scores that has scores_1 as the first row and scores_2 as the second row using np.concatenate. Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [7]:
days = ["Mon", "Tue", "Wed", "Thu", "Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]
scores = np.concatenate(([scores_1], [scores_2]))
days_np = np.array(days)
print(f"scores:\n {scores}")
print(f"Shape of scores {scores.shape}")
print(f"days:\n {days_np}")
print(f"Shape of days {days_np.shape}")

scores:
 [[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
Shape of scores (2, 5)
days:
 ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
Shape of days (5,)


#### 7. [P] Repeat the previous problem with the creation of scores from the Python lists scores_1 and scores_2, but now do it with np.vstack. The array should be identical.

In [8]:
scores = np.vstack((scores_1, scores_2))
print(scores)

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]


#### 8. [P/M] Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpy array. What is the difference in the result? In general, how does numpy deal with standard comparison operators?

In [9]:
print("Using normal python list: ", scores[:, days == "Fri"])
print("Using numpy array:\n", scores[:, days_np == "Fri"])

Using normal python list:  []
Using numpy array:
 [[7.75]
 [7.25]]


Numpy array recognizes that we are asking for the last column in the scores array as the last column in days_np array matches the masking description (days_np == "Friday"). However, when we use python list for that, it does not recognize the masking.  
In general, numpy comparison operators work element-wise, which easily gives us a masking/filter of array when we need to filter out information.

#### 9. [P] Select the scores that fell on Monday.

In [10]:
scores[:, days_np == "Mon"]

array([[9.5],
       [9. ]])

#### 10. [P] Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [11]:
scores[:, ~(days_np == "Mon")]

array([[ 8.75,  8.  , 10.  ,  7.75],
       [ 8.  , 10.  ,  8.75,  7.25]])

#### 11. [P] Select the scores that were on Tuesday or Thursday

In [12]:
scores[:, ((days_np == "Tue") | (days_np == "Thu"))]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

#### 12. [P] Show the minimum and maximum scores for the entire array of scores

In [13]:
print(f"The min score: {scores.min()}")
print(f"The max score: {scores.max()}")

The min score: 7.25
The max score: 10.0


#### 13. [P] Show the minimum scores for each week as a new array. The result should have the same dimensions (hint – use the keepdims parameter of <code>np.min</code>).

In [14]:
# for my own reference: https://www.sharpsightlabs.com/blog/numpy-axes-explained/
print(f"The min score for each week: {scores.min(axis = 1, keepdims = True)}")

The min score for each week: [[7.75]
 [7.25]]


#### 14. Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [15]:
max_days = (np.argmax(scores, axis = 1))
print(f"Days that have max score for each week: {days_np[max_days]}")

Days that have max score for each week: ['Thu' 'Wed']


#### 15. [P] Report the mean of the scores of each week

In [16]:
print(f"Mean scores for each week: {scores.mean(axis = 1)}")

Mean scores for each week: [8.8 8.6]


#### 16. [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [17]:
min_days = np.argmin(scores, axis=1)
dropped = np.delete(scores, min_days, axis = 1)
print(f"Mean after dropping scores for each week: {dropped.mean(axis = 1)}")

Mean after dropping scores for each week: [9.0625 8.9375]


#### 17. [P] Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [18]:
scores*10

array([[ 95. ,  87.5,  80. , 100. ,  77.5],
       [ 90. ,  80. , 100. ,  87.5,  72.5]])

In [19]:
np.random.seed(1234)
X = np.random.randint(1,100, 50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

#### 18. Select the first row of X

In [20]:
X[0]

array([48, 84, 39, 54, 77])

#### 19. [P] Select the last column of X

In [21]:
X[len(X) - 1]

array([97, 13, 70, 96, 32])

#### 20. [P] Select the first AND last column of X

In [22]:
X[:, (0, X.shape[1]-1)]

array([[48, 77],
       [25, 27],
       [31, 59],
       [93, 48],
       [51, 39],
       [68, 81],
       [ 4, 66],
       [76, 61],
       [47, 14],
       [97, 32]])

#### 21. [P] Select every other row of X

In [23]:
X[::2]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

#### 22. [P] Show the transpose of X, but don't change X itself

In [24]:
X.T

array([[48, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

#### 23. [P] Select the first column of X and set the result to Y.

In [25]:
Y = X[0]
print(Y)

[48 84 39 54 77]


#### 24. [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change? THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [26]:
Y[0] += 1
print(X)
print(Y)
# BOTH VALUES CHANGE!

[[49 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]
[49 84 39 54 77]


#### 25. [P] Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y again and ensure that the corresponding value of X did not change.

In [27]:
Y = X.copy()
Y[0] += 1
print(X)
# Value does not change!

[[49 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


#### 26. [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [28]:
X = np.arange(0, 10, 0.1)
X.reshape((10,10))

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

#### 27. [P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [29]:
from numpy import random
# ref: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform
rng = np.random.default_rng(1234)
X = rng.uniform(1.0, 10.0, 100)
X

array([9.7902979 , 4.42176162, 9.3092161 , 3.35523181, 3.87187353,
       2.0628211 , 3.17589664, 3.86680536, 9.67671321, 3.37284824,
       4.9690551 , 6.48883728, 8.77259167, 8.77381904, 7.07393182,
       6.93886913, 7.62181928, 3.00478292, 2.54859566, 8.83373475,
       1.54124792, 7.15320018, 7.04114217, 6.49916183, 1.54123581,
       9.79992346, 4.95056464, 5.79335519, 1.02819059, 3.26140395,
       8.72641394, 4.82768516, 7.62237095, 9.29838895, 2.38126754,
       9.93033307, 2.64098605, 9.46101612, 1.7819475 , 5.21389644,
       8.4609028 , 3.52947037, 8.8218236 , 9.78774917, 8.57542292,
       5.0398624 , 4.33457587, 5.34402493, 1.82963392, 3.04014795,
       5.82909613, 7.59908486, 5.0401971 , 3.74950693, 9.52623643,
       7.75930453, 5.24843614, 5.11548292, 7.71704023, 8.6985989 ,
       3.64151402, 7.59983049, 8.27947632, 8.98378277, 1.2234989 ,
       5.61294503, 6.51507112, 3.52314056, 5.06918554, 5.7809898 ,
       9.89771107, 1.05380352, 2.81159457, 3.31188217, 4.06670

#### 28. [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

ref: https://en.wikipedia.org/wiki/Normal_distribution.
Normal distribution represents real-valued random variables whose distribution are not known. There are two parameters for a normal distribution, the mean of the data and the variance of the data.

#### 29. [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

Law of Large Numbers: The average of the results obtained from a large number of trials should be closed to the expected value. In the case of a normal distribution, it means the more we perform the experiment, the average of the results should be close to the mean value.

#### 30. [P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers.

In [30]:
def test_normal_dist(mu, sd, vec_length, num_trials):
    rng = np.random.default_rng(1234)
    sum_dev = 0
    for i in range(num_trials):
        vec = rng.normal(mu, sd, vec_length)
        mean_vec = vec.mean()
        dev = abs(mean_vec - mu)
        sum_dev += dev
    return sum_dev/num_trials

#### 31. [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function.

In [31]:
results = np.zeros((5,2), dtype = np.single)
for i in range(1,6):
    results[i-1, 0] = 10**i
    results[i-1, 1] = test_normal_dist(0,2, 10**i, 100)
# print format - suggested by Edward Chen
np.set_printoptions(suppress=True)
results

array([[    10.        ,      0.48723024],
       [   100.        ,      0.15676601],
       [  1000.        ,      0.04989271],
       [ 10000.        ,      0.01523043],
       [100000.        ,      0.00470046]], dtype=float32)