# Lab01 - Getting Started
Name: Anh Kieu  
Class: CSCI 349 - Intro to Data Mining  
Instructor: Brian King

In [1]:
import sys
print(sys.version)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


#### 2. Did you read the syllabus? All of it? Do you agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating

I have read the syllabus, and yes, all of it. I agree to abide by the cheating rules and I am commited to honest work and Bucknell's honor code.

#### 3. What are you hoping to get out of this course?

I hope that after this course I will be more comfortable with dataframes and data extraction, manipulation and cleaning. I also hope to learn some basis in data science and machine learning models.

#### 4. Print the Python version (sys package)

In [2]:
print(sys.version)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


#### 5. Create a Python list of 10000 random integers in the range 1 to 100, using random package. Name the list x_list

In [3]:
from random import *
x_list = [randint(1,100) for x in range(10000)]

In [4]:
print(x_list[:10])

[57, 57, 56, 82, 54, 43, 61, 27, 11, 34]


#### 6. What is the minimum value of x_list? What is the max value? What is mode?

In [5]:
from statistics import mode
print("The min value of x_list is: {}.".format(min(x_list)))
print("The max value of x_list is: {}.".format(max(x_list)))
print("The mode of x_list is: {}.".format(mode(x_list)))

The min value of x_list is: 1.
The max value of x_list is: 100.
The mode of x_list is: 66.


#### 7. Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [6]:
def avg(a_list):
    return sum(a_list)/len(a_list)
print("{:.2f}".format(avg(x_list)))

50.63


#### 8. Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the range of data in widths of 10. So, x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and so on. Be sure to print x_hist at the end.

In [7]:
x_hist = [0]*10
for num in x_list:
    ind = (num - 1) // 10
    x_hist[ind] += 1
print(x_hist)

[985, 978, 988, 1017, 1007, 1027, 1007, 1001, 986, 1004]


#### 9.  What is numpy? What are its strengths? Does it have any weaknesses?

- Numpy is a Python library that helps with scientific computing as it optimizes a lot of its object types, i.e multidimensional array object compared to Python's objects. 
- Undoubtedly, numpy is more efficient when it comes to mathematical operations and computing, especially on complex objects such as multidimensional matrices or regarding complex operations like Fourie transform. 
- Personally, I think that numpy is a really useful package. It does have few "weaknesses", such as how its array object is essentially different from Python list (static vs dynamic), thus make it a bit harder to manipulate with just Python functions. Thus, it takes some learning curves and getting used to.

#### 10. [P] Import the numpy package as np and print the numpy version

In [8]:
import numpy as np
print(np.version.version)

1.19.2


#### 11. [M] What is the primary object type in numpy? Can it store data of different types? Discuss.

As quoted from **[numpy API](https://numpy.org/doc/stable/user/whatisnumpy.html)**, "at the core of the NumPy package is the ndarray object." The elements in a NumPy array are all required to be of the same data type. However, we can store arrays of objects, of which their elements are different data types from each other.

#### 12. [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types int and float in Python.

- The data types in numpy are more like C data types. For example, besides having basic types like boolean, numpy has other primitive types such as byte, short, long, single, double, or fixed size types like int8 (8 bit integer) or uint64 (64 bit unsigned integer). Numpy also has complex number type as well. 
- Even though Numpy types can be used interchangeably with Python types. However, Numpy types, or array scalars in this case work better with ndarray object as they preserve arrray type. Also, numpy scalars have a lot of method calls that arrays have.

#### 13. [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents.

In [9]:
x_list = np.array(x_list)
print(x_list)

[57 57 56 ... 76 48 26]


#### 14. [P] Redo the previous exercise, but set the data type of each value to 'float32'

In [10]:
x_list = np.array(x_list, dtype = 'float32')
print(x_list)

[57. 57. 56. ... 76. 48. 26.]


#### 15. [P] Create a length 10 integer array filled with zeros

In [11]:
z_list = np.zeros(10, dtype = int)
print(z_list)

[0 0 0 0 0 0 0 0 0 0]


#### 16. [P] Create a float array of 3 rows and 4 columns, all initialized to one.

In [12]:
o_list = np.ones((3,4), dtype = float)
print(o_list)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 17. [P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)

In [13]:
l_list = np.linspace(1,3,20)
print(l_list)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


#### 18. [P] Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 20)

In [14]:
# ref: https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng
from numpy import random
rng = np.random.default_rng(12345)
r_list = rng.integers(10, 20, (10,5))
print(r_list)

[[16 12 17 13 12]
 [17 16 16 19 13]
 [18 13 15 15 12]
 [11 12 16 16 19]
 [17 12 19 19 17]
 [16 11 10 12 14]
 [10 18 14 16 12]
 [13 11 17 17 12]
 [17 10 13 11 17]
 [13 14 14 14 12]]
